### ISSUE TITLE
Any chance of a blacklist?

### ISSUE THREAD

**Issue by brando56894** [minis-patchers/SynInvisibleHelmets#1]
I love this patcher, but every time I run it have to disable KSwigsSMP.esp, along with the three Xing SMP Hair and Wigs plugins (Fuse, HHairstyles and Dint999) because they're set as helmets so the patcher doesn't know they are actually wigs, which makes them all invisible and useless. 

Could you please add a blacklist field for plugins or disable these in your code please? The first time this happened it took me a while to figure out why the wigs weren't working. I'm sure other people have run into it as well.

**Comment by Minizbot2012** [comment]
I've added an ignore list for both esp scale down to the individual item.
